### ISSUE TITLE
Cannot instantiate interface for ComponentInterface

### ISSUE THREAD

**Issue by Chinet1** [pragmatic-modules/jslayout-parser#1]
Hi,

I found an issue with the standalone library:
because of the lack of di.xml Magento cannot create a ComponentInterfaceFactory object.
The dirty fix is adding `<preference for="Pragmatic\JsLayoutParser\Api\ComponentInterface" type="Pragmatic\JsLayoutParser\Model\Component"/>` to random di.xml in project.

Maybe there is another way to implement this inside library?

**Comment by piorus** [comment]
`Pragmatic\JsLayoutParser\Model\ComponentFactory` will do a job here. I updated a readme with the correct factory class.

**Comment by Chinet1** [comment]
Thanks, this will do the job!
